spring:
  application:
    name: hw08-mongo
mongock:
  change-logs-scan-package:
    - ru.otus.hw.mongock
  runner-type: InitializingBean
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG