spring:
  application:
    name: hw18-resilence4j
  cloud:
    openfeign:
      client:
        config:
          imoex:
            url: https://iss.moex.com/iss/
---
resilience4j:
  retry:
    instances:
      moexRetry:
        max-attempts: 3
        wait-duration: 1s
  circuitbreaker:
    instances:
      moexCB:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 1
  ratelimiter:
    instances:
      moexRL:
        limit-for-period: 3
        limit-refresh-period: 10s
        timeout-duration: 0
logging:
  level:
    ru.otus.hw.moex.FeignMoexAdapter: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG
    io.github.resilience4j.retry: DEBUG
    io.github.resilience4j.ratelimiter: DEBUG