spring:
  application:
    name: hw13-security-acl
  datasource:
    url: jdbc:h2:mem:maindb
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog.xml
  mvc:
    hiddenmethod:
      filter:
        enabled: true